### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [yichenkung/git-workshop#1]
也謝謝你分享了你的心得，軟體工作蠻大部分是需要透過團隊協作的，生涯中不乏看到技術能力很強、卻無法與他人合作的工程師，只能說「一個人走得快，一群人走得遠」，在我看來，團隊協作能力的重要性是跟技術能力差不多的，在累積技術能力之餘，也不忘繼續精進溝通能力，這樣是很棒的。

至於年紀這件事，我在另外一本關於大腦與學習的書裡有讀到過：人的大腦並不是固定的，人的大腦其實像肌肉一樣，既然可以透過運動與重訓來訓練肌肉，那大腦也是可以被訓練的，所以過去的經歷，並不代表你未來的能力，但就是看你要不要開始訓練自己的大腦。

這跟我們這次看的這部影片應該有相呼應到，所以不要讓年紀成為我們的阻礙～

**Comment by yichenkung** [comment]
謝謝老師的鼓勵，我會努力的。
